apiVersion: apps/v1
kind: Deployment
metadata:
  name: plantgame-http_server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plantgame-http_server
  template:
    metadata:
      labels:
        app: plantgame-http_server
    spec:
      containers:
      - name: plantgame-http_server-container
        image: johanneshoelker/http-server:test
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: plantgame-http-service
spec:
  selector:
    app: plantgame-http
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plantgame-http-ingress
spec:
  rules:
    - host: plantgame-http_server
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: plantgame-http-service
                port:
                  number: 5000
