apiVersion: apps/v1
kind: Deployment
metadata:
  name: plantgame-rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plantgame-rabbitmq
  template:
    metadata:
      labels:
        app: plantgame-rabbitmq
    spec:
      containers:
      - name: plantgame-rabbitmq
        image: rabbitmq:3.8-management
        ports:
        - containerPort: 5672
        - containerPort: 15672
---
apiVersion: v1
kind: Service
metadata:
  name: plantgame-rabbitmq-service
spec:
  selector:
    app: plantgame-rabbitmq
  ports:
    - name: rabbitmq
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: rabbitmq-management
      protocol: TCP
      port: 15672
      targetPort: 15672
