apiVersion: apps/v1
kind: Deployment
metadata:
  name: plantgame-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plantgame-backend
  template:
    metadata:
      labels:
        app: plantgame-backend
    spec:
      containers:
      - name: plantgame-backend-container
        image: johanneshoelker/plantgame-backend:0.2.13
        imagePullPolicy: Always
